[color]

background = #1e1e2e
foreground = #cdd6f4
transparent = #1e1e2e7f
sep = #45475a

white = #cdd6f4
black = #11111b
red = #f38ba8
green = #a6e3a1
yellow = #f9e2af
blue = #89b4fa
purple = #b4befe
cyan = #94e2d5
pink = #f5c2e7
orange = #fab387

; [color]

; background = ${xrdb:background}
; foreground = ${xrdb:foreground}
; transparent = ${xrdb:transparent}
; sep = ${xrdb:sep}

; white = ${xrdb:white}
; black = ${xrdb:black}
; red = ${xrdb:red}
; green = ${xrdb:green}
; yellow = ${xrdb:yellow}
; blue = ${xrdb:blue}
; purple = ${xrdb:purple}
; cyan = ${xrdb:cyan}
; pink = ${xrdb:pink}
; orange = ${xrdb:orange}
